version: 0.2
env:
  variables:
    REPO_NAME:                "monorepo"
  parameter-store:
    SAM_S3_BUCKET:            "/monorepo/build/SAM_S3_BUCKET"

phases:
  install:
    commands:
      - npm install -g swagger-cli
      - npm install -g dredd --unsafe-perm=true
      - pip install awscli aws-sam-cli bandit coverage dredd-hooks prospector==1.1.6.2 pylint_quotes aws-lambda-decorators
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yaml
      - swagger-cli validate swagger.yaml
      - bandit -r .
      - prospector
      - coverage run --branch --source='.' -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*
  build:
    commands:
      - export CLEAN_PR=`echo $CODEBUILD_SOURCE_VERSION | tr '/' '-'`
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET/
      - sam build -s src
      - sam package --s3-bucket $SAM_S3_BUCKET --output-template-file NewSamTemplate.yaml
      - sam deploy --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name ${REPO_NAME}-stack --parameter-overrides ApiNameSuffix=-$CLEAN_PR S3Bucket=$SAM_S3_BUCKET
      - dredd swagger.yaml https://r1pipevhy8.execute-api.eu-west-2.amazonaws.com --hookfiles tests/hooks.py --language python --names