version: 0.2
env:
  variables:
    REPO_NAME:                "monorepo"
  parameter-store:
    SAM_S3_BUCKET:            "/monorepo/build/SAM_S3_BUCKET"

phases:
  install:
    commands:
      - npm install -g swagger-cli
      - npm install -g dredd --unsafe-perm=true
      - pip install awscli aws-sam-cli bandit coverage dredd-hooks prospector==1.1.6.2 pylint_quotes aws-lambda-decorators
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yaml
      - swagger-cli validate swagger.yaml
      - bandit -r .
      - prospector
      - coverage run --branch --source='.' -m unittest tests/test_*.py
      - coverage run --branch --source='.' -m unittest tests/*/test_*.py
      - coverage report -m --fail-under=100 --omit=tests/*,it/*
  build:
    commands:
      - export CLEAN_PR=`echo $CODEBUILD_SOURCE_VERSION | tr '/' '-'`
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET/$CLEAN_PR/
      - sam build -s src
      - sam package --s3-bucket $SAM_S3_BUCKET --s3-prefix $CLEAN_PR --output-template-file NewSamTemplate.yaml
      - sam deploy --s3-bucket $SAM_S3_BUCKET --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name ${REPO_NAME}-stack-${CLEAN_PR} --parameter-overrides RepoName=${REPO_NAME} ApiNameSuffix=-$CLEAN_PR S3Bucket=$SAM_S3_BUCKET/$CLEAN_PR
      - export api_id=`aws apigateway get-rest-apis --query "items[?name=='${REPO_NAME}-apis-${CLEAN_PR}'].id" | jq first | tr -d '"'`
      - dredd swagger.yaml https://${api_id}.execute-api.${AWS_REGION}.amazonaws.com/Prod --hookfiles tests/hooks.py --hookfiles tests/a_lambda/hooks.py --hookfiles tests/b_lambda/hooks.py --language python
      - coverage run --branch --source='.' -m unittest it/test_*.py