version: 0.2
env:
  variables:
    REPO_NAME:                "python-serverless-template"
  parameter-store:
    SAM_S3_BUCKET:            "/python-serverless-template/build/SAM_S3_BUCKET"

phases:
  install:
    commands:
      - pip install -U -q pip
      - pip install -q awscli aws-sam-cli aws-lambda-decorators yq
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
  build:
    commands:
      - aws s3 cp swagger.yaml s3://$SAM_S3_BUCKET/
      - chmod u+x ./packager.sh
      - bash ./packager.sh -q
      - sam build -s .build
      - sam package --s3-bucket $SAM_S3_BUCKET --output-template-file NewSamTemplate.yaml
      - sam deploy --s3-bucket $SAM_S3_BUCKET --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --template-file NewSamTemplate.yaml --stack-name ${REPO_NAME}-stack --parameter-overrides RepoName=${REPO_NAME} S3Bucket=$SAM_S3_BUCKET