AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Build template for Dev and Staging projects

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Service"
        Parameters:
          - ServiceName
          - AlertEmail
      - Label:
          default: "GitHub Configuration"
        Parameters:
          - GitHubOwner
          - GitHubRepo
          - GitHubToken
    ParameterLabels:
      ServiceName:
        default: Service Name
      AlertEmail:
        default: Email
      GitHubOwner:
        default: Repo Owner
      GitHubRepo:
        default: Repo Name
      GitHubToken:
        default: Personal Access Token

Parameters:
  ServiceName:
    Description: Enter a lower case, high level service name without environment details. Used to autofill service names. For example, your-service-name
    Type: String
  AlertEmail:
    Description: Email address to send staging build alerts to, or example you@example.com
    Type: String
  GitHubOwner:
    Description: Owner of git repo to clone, for example gridsmartercities
    Type: String
  GitHubRepo:
    Description: Repo to clone, for example python-serverless-template
    Type: String
  GitHubToken:
    Description: The value of a GitHub Personal Access Token that has an API access to your repo
    Type: String

Resources:

  # Parameters
  GitHubOwnerParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_OWNER
      Type: String
      Value: !Sub ${GitHubOwner}
  GitHubRepoParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_REPO
      Type: String
      Value: !Sub ${GitHubRepo}
  GitHubTokenParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_TOKEN
      Type: String
      Value: !Sub ${GitHubToken}
  SamS3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${ServiceName}/build/SAM_S3_BUCKET
      Type: String
      Value: !Sub ${ServiceName}-${AWS::Region}-output

  # S3
  CodebuildOutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-${AWS::Region}-output
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CodebuildCachingS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-${AWS::Region}-pip-cache
      LifecycleConfiguration:
        Rules:
          - Id: CacheExpiry
            Status: Enabled
            ExpirationInDays: 03
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Code Build Failure rule
  CodebuildFailedBuildEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ServiceName}-build-event-rule
      Description: Fire an event when a staging build fails
      EventPattern:
        source:
          - aws.codebuild
        detail-type:
          - Codebuild Build State Change
        detail:
          build-status:
            - FAILED
          project-name:
            - !Ref CodebuildStgProject
      Targets:
        - Arn: !Ref CodebuildAlarmTopic
          Id: !Sub ${ServiceName}-build-event-rule-target

  # Code Buld Alarms
  CodebuildAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${ServiceName}-codebuild-alarms
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email

  # Code Build Projects
  CodebuildDevProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ServiceName}-dev
      ServiceRole: !GetAtt CodebuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
      Source:
        Auth:
          Type: OAUTH
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        Type: GITHUB
        BuildSpec: buildspec-dev.yaml
      Cache:
        Type: S3
        Location: !Ref CodebuildCachingS3Bucket
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
      TimeoutInMinutes: 10
  CodebuildStgProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ServiceName}-stg
      BadgeEnabled: true
      ServiceRole: !GetAtt CodebuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
      Source:
        Auth:
          Type: OAUTH
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        Type: GITHUB
        BuildSpec: buildspec-stg.yaml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/master$
      TimeoutInMinutes: 10

  # Permissions
  CodeBuildSharedPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ServiceName}-codebuild-shared-service-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ops.apigateway.amazonaws.com/AWSServiceRoleForAPIGateway
          - Effect: Allow
            Action: ssm:GetParameters
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/SAM_S3_BUCKET
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_OWNER
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_REPO
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_TOKEN
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:List*
              - s3:DeleteObject
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:DeleteRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PassRole
              - iam:PutRolePolicy
              - iam:GetRolePolicy
              - iam:DeleteRolePolicy
              - iam:UpdateAssumeRolePolicy
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${ServiceName}-*
          - Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:GetFunctionConfiguration
              - lambda:DeleteFunction
              - lambda:AddPermission
              - lambda:UpdateFunctionCode
              - lambda:RemovePermission
              - lambda:ListTags
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:UpdateFunctionConfiguration
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ServiceName}-stack-*
          - Effect: Allow
            Action:
              - apigateway:PUT
              - apigateway:POST
              - apigateway:PATCH
              - apigateway:DELETE
              - apigateway:GET
            Resource: !Sub arn:aws:apigateway:${AWS::Region}::/restapis*
          - Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
              - cloudformation:GetTemplateSummary
              - cloudformation:ListStacks
              - cloudformation:CreateChangeSet
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:ExecuteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:DeleteStack
            Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ServiceName}-*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DeleteLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - SNS:CreateTopic
              - SNS:GetTopicAttributes
              - SNS:Subscribe
              - SNS:DeleteTopic
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DeleteAlarms
            Resource: "*"
      Roles:
        - !Ref CodebuildRole
  CodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-codebuild-dev-service-role
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole
  AmazonAPIGatewayPushToCloudWatchLogs:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${AWS::Region}-logs-apigateway-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  # Api Gateway Account
  Account:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt AmazonAPIGatewayPushToCloudWatchLogs.Arn

  # Log Groups
  CodebuildDevLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${CodebuildDevProject}
  CodebuildStgLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${CodebuildStgProject}
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/welcome
